/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedSubmitRouteImport } from './routes/_authed.submit'
import { Route as AuthedDashboardRouteImport } from './routes/_authed.dashboard'
import { Route as AuthedApprovalsRouteImport } from './routes/_authed.approvals'
import { Route as AuthedAllRecordsRouteImport } from './routes/_authed.all-records'
import { Route as AuthedActivityRouteImport } from './routes/_authed.activity'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSubmitRoute = AuthedSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedApprovalsRoute = AuthedApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAllRecordsRoute = AuthedAllRecordsRouteImport.update({
  id: '/all-records',
  path: '/all-records',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedActivityRoute = AuthedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/activity': typeof AuthedActivityRoute
  '/all-records': typeof AuthedAllRecordsRoute
  '/approvals': typeof AuthedApprovalsRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/submit': typeof AuthedSubmitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/activity': typeof AuthedActivityRoute
  '/all-records': typeof AuthedAllRecordsRoute
  '/approvals': typeof AuthedApprovalsRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/submit': typeof AuthedSubmitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/activity': typeof AuthedActivityRoute
  '/_authed/all-records': typeof AuthedAllRecordsRoute
  '/_authed/approvals': typeof AuthedApprovalsRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/submit': typeof AuthedSubmitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/activity'
    | '/all-records'
    | '/approvals'
    | '/dashboard'
    | '/submit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/activity'
    | '/all-records'
    | '/approvals'
    | '/dashboard'
    | '/submit'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/_authed/activity'
    | '/_authed/all-records'
    | '/_authed/approvals'
    | '/_authed/dashboard'
    | '/_authed/submit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/submit': {
      id: '/_authed/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof AuthedSubmitRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/approvals': {
      id: '/_authed/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AuthedApprovalsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/all-records': {
      id: '/_authed/all-records'
      path: '/all-records'
      fullPath: '/all-records'
      preLoaderRoute: typeof AuthedAllRecordsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/activity': {
      id: '/_authed/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthedActivityRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedActivityRoute: typeof AuthedActivityRoute
  AuthedAllRecordsRoute: typeof AuthedAllRecordsRoute
  AuthedApprovalsRoute: typeof AuthedApprovalsRoute
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedSubmitRoute: typeof AuthedSubmitRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedActivityRoute: AuthedActivityRoute,
  AuthedAllRecordsRoute: AuthedAllRecordsRoute,
  AuthedApprovalsRoute: AuthedApprovalsRoute,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedSubmitRoute: AuthedSubmitRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
